services:
  - type: web
    name: suriorder
    env: node
    buildCommand: npm install && node seed.js
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://suriorder.onrender.com
      - key: JWT_SECRET
        value: CsLi9DYEgYxHoh88L80yKkgp2GY4da5kn6sK1L5WY8k
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
